project:
  type: website
  render:
    - "index.qmd"
    - "!r_demos/"
    - "!presentations/"
  resources:
    - r_demos/**
    - "presentations/"

website:
   title: "420m"
   site-url: "https://monaxue.github.io/420m/"