project:
  output-dir: docs # "docs" is an important folder name for GitHub pages
  type: website
  execute-dir: project
  resources:
    - data/

website: 
  title: "PSYCH 420m Lab"
  search: false
  navbar: 
    pinned: true
    left:
      - href: index.qmd
        text: Slides
      - href: files/cheatsheet.qmd
        text: R Cheatsheet
      - href: files/casestudy4.qmd

execute:
  cache: true

format:
  html:
    css: noAI.css
  
filters: 
  - after-header-note.lua
  - filelink.lua