project:
  output-dir: docs # "docs" is an important folder name for GitHub pages
  type: website
  execute-dir: project
  resources:
    - data/
    - _rmd_fa26/

website: 
  title: "PSYCH 420m Lab"
  search: false
  navbar: 
    pinned: true
    left:
      - href: index.qmd
        text: Labs
      - href: files/cheatsheet.qmd
        text: R Cheatsheet
  #announcement: 
    #icon: info-circle
    #dismissable: false
    #content: "**Alert** - Case Study 4 due date changed to Wed. 4-29. Please email me if another date works better for you!"
    #type: primary
    #position: below-navbar

execute:
  cache: true

format:
  html:
    css: noAI.css
  
filters: 
  - after-header-note.lua
  - filelink.lua