
# Week 6


::: notes

Go over case studies.

Cover z-scores and CI. Have people write an interpretation for CI's for their lab report. Have people revise their lab reports.

:::

## Case studies

::: card-list

- Overall:

- Primary reason why people lost points:

- What people struggle with:
    - Hypotheses and grouping data
    - What you can/caonnot infer with descriptive statistics

:::

::: header
Case studies | Research questions, hypotheses, methods
:::

## Research questions, hypotheses, methods
::: card-list
- For this class, I don't care about the truthfulness of a statement as much as the logic.
:::

# Interpretations

## "Ambiguous thinking"

::: header
Case studies | Interpretations
:::

::: card-list
- Descriptive statistics is all about "ambiguous thinking"
    - Shape: Is it normal? Symmentrical? Skewed (rarer than you think!)? Bimodal?
    - Center ~ ***Sample*** mean
    - Spread ~ ***Sample*** SD
:::

## "Ambiguous thinking"

::: header
Case studies | Interpretations
:::

```{r}

set.seed(1)

n=50
x = c()
experiment = c()

for (i in 1:3){
    x = c(x, rbinom(n=n, size = 20, prob = 0.5))
    experiment <- c(experiment, rep(i, times=n))
}

df <- tibble(x=x, experiment=experiment)

ggplot(df, aes(x=x)) + geom_histogram() + facet_wrap(~experiment)

```

## Different purposes

::: header
Case studies | Interpretations
:::

::::: columns

:::: column
### Descriptive
::: card-list
- Visualize the ***general*** shape, center, and spread of the ***sample***
- "See the forest, but not the trees"
:::

::::

:::: column
### Inferential

::: card-list

- Make inferences about the true population means

:::
::::
:::::



## What I saw in the case studies

::: header
Case studies | Interpretations
:::

::: card-list

- Statements that imply a population level conclusion
- WRONG: "A histogram will let me compare the performance of each group"
- When you talk about "performance" you are implying knowledge about the true population
    - "Score" (noisy metric for performance) vs. "Performance" (true population)

:::

## Score vs. Performance

::: header
Case studies | Interpretations
:::

::: card-list

- Score is the thing we can measure. "Performance" is the thing we actually care about that we hope the score represents.
- Example
    - An IQ test wishes to measure your intelligence, but at best it only captures part of your intelligence. What it also captures includes: your education, your wealth, whether or not you were exposed to lead as a kid, etc.
    - If you say "there is a difference in intelligence between group 1 and group 2", then you are implying a population difference. If you say "there is a difference in sample mean of IQ test scores between group 1 and group 2"

:::

## Correct mean interpretations from a histogram/summary table

::: header
Case studies | Interpretations
:::

- Sufficient: "The ***sample*** mean of the score in group A is _ and the ***sample*** mean of the score in group B is _."
- If you want to compare: 
    - Don't forget ***sample mean*** and ***score*** (or whatever the actual metric is in the study)

## Why can't we talk about the population when looking at histograms?

::: header
Case studies | Interpretations
:::

::: card-list

- A difference in the mean could be due to sampling error
- What inferential statistics does: It takes into consideration the possible sampling errors
    - But CIs are ***not*** errors!
    - How? Sampling distributions provide us with the math to make a good guess

:::

## 


## Confidence interval review

::: card-list

- Explore the [Confidence Interval Simulator](https://shiny.rit.albany.edu/stat/confidence/) (this link is also on the website).

- Discuss with your neighbors:

    - What do you observe?

    - Keep in mind: the difference between the population mean and the sample mean.

    - Based on your observations, what do you think a confidence interval is?

:::

## What is a 95% confidence interval? Answer:

::: card-list

- 95% of the samples generated by a population with the true mean, $\mu$, will have a CI that contains $\mu$.

- WRONG: There is a 95% probability that the CI contains the true mean, $\mu$.

    - This is different from the first statement
    - You cannot actually calculate this probability directly, because it requires that you know the true mean, $\mu$

- Therefore, we instead use the term "confident". We say that we are 95% confident that the CI contains the true mean.
    - There is a reason why it is called the confidence interval, and not the probability interval.
:::


<!--

```{=html}
<iframe src="https://wall.sli.do/event/psqmdehPARDpce13BWS1LY/?section=b87f4381-4b7d-41fd-abd0-76f5f34870db" height=600 width=100%></iframe>
```

-->

## IMPORTANT: Writing CI interpretations

**You want to write your CI interpretation almost exactly like the following:**

The 95% confidence interval is [33.92, 34.88]. This means that we are 95% confident that the true mean lies within [33.92, 34.88].

...

Because the confidence intervals do not overlap, we can be fairly confident that the true means of females and males are different.

##

I'm sorry guys, yeah, stats can be super annoying where it feels like you have to say things exactly right. I wish I could measure understanding without words. But my hope is that what you take away is an intuition about how data actually works, instead of just trying to memorize a bunch of little rules. 

<!--

## Formatting Essentials

```{=html}
<iframe src="https://wall.sli.do/event/psqmdehPARDpce13BWS1LY/?section=b87f4381-4b7d-41fd-abd0-76f5f34870db" height=600 width=100%></iframe>
```

-->


# Deliverables

::: card-list
- Write a reflection
    - [ ] How you did you feel you did on this first case study? What are you proud of? What do you think you can improve upon?
    - [ ] What are your major the major takeaways from today's class?
    - [ ] What revisions would you make on your case study? Be specific.
    - [ ] What do you want your future self to remember when working on future case studies? (Even if you mayber remembered this time)
- Write a CI interpretation for your Case Study 1.
    - [ ] What are the major differences between a descriptive and inferential statistics?
    - [ ] What is the definition of a CI?
    - [ ] What does the CI say about the results? (Do you not use the word "significant"!)

- Write a 
- In a nicely formatted RMarkdown file, critique your own case study by applying the concepts we learned today. 
	- Improve one of your case study plot. Explain what you changed and why.
	- In a paragraph, describe what you would change in your interpretation of results, e.g., This is what I said... This is what I would say now.
:::


