## Case Study 2

:::: panel-tabset

## Option 1

### Natural Light and Depression

[Dataset for Option 1](/data/CaseStudy2_NaturalLightDepression.csv){.filelink}

You work at a data science consulting firm and your biggest client is Dell Inc., a large technology corporation located in the Austin area. Dell has publicly committed to their employees’ mental well-being and have been examining their workplace policies to identify any potentially problematic practices. To that end, each Dell employee has been asked to anonymously fill out Beck’s Depression Inventory, which contains 21 questions and results in a depression score ranging from 0 to 63. Anyone scoring 14 points or higher is considered to have at least mild symptoms of depression.

Your firm has been contracted to identify if there are any office features that could be affecting employee mental health. The office feature you have been assigned to examine is the presence (versus absence) of outdoor-facing windows. Approximately 1 out of every 3 offices in their buildings have such windows, and each employee is randomly assigned to an office when they are hired.

You have been sent the data from one of Dell’s biggest office buildings, containing 800 de-identified employee records. Each row indicates one employee’s depression score and whether their office has windows or not. Your primary objective is to test whether employees with office windows have systematically different depression scores compared to employees without office windows. Furthermore, give Dell a recommendation regarding their office policy.

Do the employees from either type of office appear to reach the threshold to be considered mildly depressed? If so, they may need to consider taking action to lower employee depression levels for one or both of the employee groups. 


## Option 2

### Testosterone Replacement and Stress

[Dataset for Option 2](/data/CaseStudy2_TestosteroneReplacement.csv){.filelink}

You work as a data scientist for a clinic that recently received a grant to study the potential for testosterone replacement therapy to boost cortisol levels. Practitioners are concerned that a commonly used treatment could increase in serum cortisol, a stress related hormone. High levels of cortisol (above 25 mcg/dL) have been shown to be associated with weight gain, insomnia, and high blood pressure.

The clinic has run a randomized study in which people were assigned to one of two conditions, a placebo condition and a drug condition. After two weeks of treatment, participants returned to the clinic and a fasting blood sample was taken in the morning. The blood sample was used to measure the levels of cortisol for each participant. Your primary objective is to test if participants who received the drug treatment have higher levels of serum cortisol in comparison to the placebo condition. Furthermore, are those levels of cortisol high enough to warn against the use of this drug?

## Rubric (overview)

### Overview (15 points total)

1. Formatting: Submit an html file generated by Rmd that is well formatted and organized (1 point)
1. Research Question and Hypotheses (2 points)
1. Methods Overview (2 points)
1. Results and Interpretation (6 points)
1. External sources (4 points)

## Detailed Rubric

### Detailed Rubric

**Formatting** (1 point)

- [ ] Submit an html file generated by Rmd that is well formatted and organized (1 point)

**Research Question and Hypotheses** (2 points)

Include 1-2 sentences for each of the following:

- [ ] The research questions (there are two)
- [ ] The main hypotheses
- [ ] The null hypotheses

**Methods Overview** (2 points)

- [ ] Explain how the the research question informs your methedological choices. For instance, why did you chose to compare certain groups? 
- [ ] What is the purpose of a null hypothesis, and how does it relate to the main hypothesis?
- [ ] What plots and statistical analyses will you be conducting to answer the research question? Why did you choose them?

**Results and Interpretation** (6 points)

- [ ] At least one summary table, including sample sizes, means, SDs, SEs. (1 point)
- [ ] At least one descriptive plot (1 point)
- [ ] One inferential plot (1 point)
- [ ] A few sentences reporting key results, i.e., the means, sd, confidence intervals, p-values. (1 point)
- [ ] Interpretations (2 points)
    - [ ] What is the *main* purpose of descriptive vs. inferential statistics?
    - [ ] Include appropriate interpretations for your plots (don't overinterpret!)
    - [ ] Define key terms, like CIs and p-values.
    - [ ] What conclusions can you draw about the data, and what can you use to support your conclusions?
    - [ ] Do not use the term "significant"!


**External sources section** (4 points)

The case studies can be completed without using any external sources. However, if you choose to use them, you must be able to justify the choice. Points will be deducted if you use content not covered in class and do not explain them in this section. 

- [ ] List every line of code and statistical concept that we have not covered in class, and explain:
    - [ ] What they do or mean
    - [ ] Why you have chosen to use this in place of what we learned in class
    - [ ] A link to the source, if it exists, otherwise a description is fine.

*If you do not use any external sources, just say "Did not use external sources."*

## Hints

### Hints

**Hypotheses**

Both options will require 2 main hypotheses: 

1. The first is something about the difference between groups.
2. The second is about whether the observed means are greater than a certain threshold. 

The two null hypotheses would be the opposite of those.

You do not need to conduct a simulation to test the hypotheses. The `t.test()` function will be sufficient.

**CIs and t-tests**

- For the first hypothesis: use both CIs and p-values to support your conclusions.
- For the second hypothesis: you can choose to only use CIs to support your conclusions. 
- Extra credit: you will receive one extra credit if you choose to also use a t-test to support your second hypothesis.


**Extra credit** (1 point)

You will receive one extra credit if you do a t-test for you second hypothesis.

1. Make sure to do the t-test for both groups. The easiest way to do this is to add it into your summary table.
2. You will need to run a "one-sample" t.test for the second hypothesis. To do so, you will need to specify two additional parameters in the `t.test()` function.

```r

... %>% mutate(h2_p.value = t.test(column_name, mu=..., alternative = ...)$p.value)

```

- `mu` specifies your null hypothesis (threshold value).
- `alternative` specifies your main hypothesis. It can take the value of "two.sided", "less", or "greater".
    - "two.sided" means the main hypothesis is "outside" (on either side) of the null hypothesis (what we did in [Lab 7](/presentations/week7.qmd){.filelinke}). This is the default value for `alternative` if you don't     specify a value.
    - "less" means that the main hypothesis is less than the null hypothesis.
    - "greater" means that the main hypotehsis is greater than the null hypothesis.

To help you choose your alternative hypothesis, I have skectched the sampling distribution representation of the p-value below.

```{r}
#| echo: false
#| fig-cap: "A sketch of the p-value for the second main hypothesis."

source("_scripts/area_under_norm.R")

`mu[threshold]` <- 0
`bar(x)[observed]` <- 1.5

area_under_norm(mu=`mu[threshold]`, sd=1, type="right", bounds=c(`bar(x)[observed]`), show_percent = FALSE) + labs(title="Sampling Distribution")

```

**Relevant slides**

- Hypothesis generation: [Lab 7](/presentations/week7.qmd)
- Descriptive vs. Inferential statistics: [Lab 4](/presentations/week4.qmd), [Lab 6](/presentations/week6.qmd)
- Plots: [Lab 4](/presentations/week4.qmd)
- Histogram interpretations: [Lab 4](/presentations/week4.qmd), [Lab 6](/presentations/week6.qmd)
- CI calculation and interpretations: [Lab 4](/presentations/week4.qmd), [Lab 6](/presentations/week6.qmd), [Lab 7](/presentations/week7.qmd), [Online simulation](https://shiny.rit.albany.edu/stat/confidence/)
- p-value calculation and interpretations: [Lab 7](/presentations/week7.qmd)

::::