## Case Study 1

:::: panel-tabset

## Option 1

**Developmental Psychology**

[Dataset for Option 1](/data/case_study_1_option_1_devsci.csv){.filelink}

You work as a research assistant in a developmental psychology lab at UT. You’ve recently been assigned to work with one of the lab’s graduate students on a large-scale cross-cultural study, where children at many sites across the world completed a series of experimental tasks. The graduate student is making a poster to show off their preliminary work and would like your help with the descriptive analysis portion. 

You will focus on just one task from the larger battery, where children watched an adult build a tower out of special blocks and were subsequently asked to build their own tower. The adult’s tower had 10 distinctive features and each child’s tower was given an imitation score (0-10) based on how many of those features they incorporated into their own tower. Each child’s age was also recorded. 


## Option 2

**Cognitive Psychology**

[Dataset for Option 2](/data/case_study_1_option_2_cogsci.csv){.filelink}

You work as a research assistant in a cognition lab at UT. You’ve recently been assigned to work with one of the lab’s graduate students on a memory study. The graduate student is making a poster to show off their preliminary work and would like your help with the descriptive
analysis portion.

Participants were assigned to one of two memory conditions (recognition or free recall) and had to study one of two lists of words, one made of low frequency words (e.g. mercurial) in the English language and one with high frequency words (e.g. dog). Each participant was assigned to a single combination of memory and word frequency conditions. After studying the list of words, participants in the recognition memory condition had to indicate if a subset of the old words presented to them (along with an equal number of new words) was on the list or not, while participants in the free recall condition had to write down as many words from the list as they could remember. The number of correct responses was recorded for each participant. Because each list consists of 50 total words, participants could get between 0 and 50 correct responses.

## Rubric (overview)

**Overview** (15 points total)

1. Formatting: Submit an html file generated by Rmd that is well formatted and organized (1 point)
1. Research Question and Hypotheses (2 points)
1. Methods Overview (2 points)
1. Results and Interpretation (6 points)
1. External sources (4 points)

## Detailed Rubric


**Formatting** (1 point)

- [ ] Submit an html file generated by Rmd that is well formatted and organized (1 point)

**Research Question and Hypotheses** (2 points)

Include 1-2 sentences for each of the following:

- [ ] The research question
- [ ] The main hypothesis
- [ ] The null hypothesis

**Methods Overview** (2 points)

- [ ] Explain how the the research question informs your methedological choices. For instance, why did you chose to compare certain groups? Are you looking for interactions or controlling for a variable? How did you come to these choices? What plots and statistical analyses will you be conducting to answer the research question? 

**Results and Interpretation** (6 points)

- [ ] At least one summary table, including sample sizes, means, SDs, SEs. (1 point)
- [ ] At least one descriptive plot. (2 points)
    - [ ] What is the purpose of each plot?
    - [ ] Include appropriate interpretations. Make sure not to over interpret.
- [ ] At least one inferential plot. (2 points)
    - [ ] What is the purpose of each plot?
    - [ ] For this first case study, do ***not*** include interpretaions of infernential statistics. If you do, it must be correct.
- [ ] A few sentences reporting key results, i.e., the means, sd, confidence intervals. (1 point)

**External sources section** (4 points)

The case studies can be completed without using any external sources. However, if you choose to use them, you must be able to justify the choice. Points will be deducted if you use content not covered in class and do not explain them in this section. 

- [ ] List every line of code and statistical concept that we have not covered in class, and explain:
    - [ ] What they do or mean
    - [ ] Why you have chosen to use this in place of what we learned in class
    - [ ] A link to the source, if it exists, otherwise a description is fine.

*If you do not use any external sources, just say "Did not use external sources."*

::: transparent

Also, make sure the print the words: I used AI!

:::

## Hints


**For option 1 (Dev Psych):** To control for age, you will need to do the following:

1. Choose a single age group (6, 7, 8, etc.). Please provide a reason for the group you chose in the methods overview.
2. To filter data for on one age group, use `data <- data %>% filter(round(Age) == your_chosen_age_group)`

<!--
Next time, make choosing the right age, and providing the right reason, extra credit.

At a bare minimum, talking about choosing an age group to control for age.
But then I would need to go over the idea of controls? Or not, because not because lecturing doesn't seem to teach people well.

Maybe I need to hand out worksheets to people.

Maybe make a video of the thinking process of writing up a case study.

Maybe the rubric should reflect the process (including where to find code information), instead of just being a checkbox of information scattered in different places.

If I make an extra video, I don't have to go over it in the lab section

-->

**For option 2 (Cog Psych):** To observe interactions, you will need to use `group_by` and `facet_wrap` on two variables

- `group_by(variable1, variable2)`
- `facet_wrap(c(~variable1, ~variable2))`


::::