---
echo: false
warning: false
---

## Case Study 4

:::: panel-tabset

## Memory Decline

[Dataset](/data/mental-rotation.csv){.filelink}

You work as a statistical consultant for a medical care corporation, and part of your job is to
assess patients’ cognitive abilities. Your company is testing out a perceptual task that involves
mental rotation, which is the ability to imagine what an object would look like from a different
perspective. During the task, the patient is first shown an image of an object and then is asked
to determine if a second presented object is the same as the first – merely rotated – or an
entirely new object. They complete 100 such trials, 50 where the objects are the same and 50
where they are different. (See the figure below for an example.)

Your company would like to use this task to help diagnose individuals that have undergone
cognitive decline. Previous research has established that in healthy individuals, the speed (in
milliseconds) at which someone can identify that the second object is the same as the first
depends on how much the object has been rotated (measured in degrees); moreover, the
relationship is approximately linear. For impaired individuals, the relationship between speed
and degree of rotation is approximately flat (i.e., they are unassociated).

Five patients have completed the task described above. Since you are only interested in the
cases where the two objects were indeed the same, you have only been given the 50 trials from
that condition. Analyzing each patient individually, plot the completion time as a function of the
degree of rotation and produce an estimate of the slope (including a 95% confidence interval).
Your company would like to know which patients, if any, show evidence of cognitive decline.
Produce a short report where you summarize the data, present descriptive results, and draw
conclusions about each patient’s cognitive status.

## Rubric (overview)

### Overview (15 points total)

1. Formatting: Submit an html file generated by Rmd that is well formatted and organized (1 point)
1. Research Question and Hypotheses (2 points)
1. Methods Overview (2 points)
1. Results and Interpretation (7 points)
1. External sources (3 points) 

## Detailed Rubric

### Detailed Rubric

**Formatting** (1 point)

- [ ] Submit an html file generated by Rmd that is well formatted and organized (1 point)

**Research Question and Hypotheses** (2 points)

Include 1-2 sentences for each of the following:

- [ ] The research questions (there are two)
- [ ] The main hypotheses
- [ ] The null hypotheses

**Methods Overview** (2 points)

- [ ] Explain how the the research question informs your methedological choices. For instance, why did you chose to compare certain groups? 
- [ ] What is the purpose of a null hypothesis, and how does it relate to the main hypothesis?
- [ ] What plots and statistical analyses will you be conducting to answer the research question? Why did you choose them?

**Results and Interpretation** (8 points)

- [ ] One summary table, including sample sizes, means, SDs, SEs. (1 point)
- [ ] One descriptive plot (1 point)
- [ ] One inferential plot (1 point)
- [ ] A few sentences reporting key results, i.e., the means, sd, confidence intervals, p-values. (1 point)
- [ ] Interpretations (3 points)
    - [ ] What is the *main* purpose of descriptive vs. inferential statistics?
    - [ ] Include appropriate interpretations for your plots (don't overinterpret!)
    - [ ] Based on the data, what conclusions can you draw about the population?
    - [ ] Support your conclusions using the proper statistical concepts. 
        - [ ] Correctly define each statistical concept.
        - [ ] Interpret your results based on these statistical concept and its definition. Make sure to use precise language. For example, do not use terms that imply probability when that is not part of the definition of the concept.
    - [ ] Do not use the term "significant"!
 - [ ] Make the proper effect size recommendation, and explain your reasoning. See hints. (1 point)


**External sources section** (2 points)

The case studies can be completed without using any external sources. However, if you choose to use them, you must be able to justify the choice. Points will be deducted if you use content not covered in class and do not explain them in this section. 

- [ ] List every line of code and statistical concept that we have not covered in class, and explain:
    - [ ] What they do or mean
    - [ ] Why you have chosen to use this in place of what we learned in class
    - [ ] A link to the source, if it exists, otherwise a description is fine.

*If you do not use any external sources, just say "Did not use external sources."*

## Hints

The inferential plot will be different than usual.

### Relevant slides

- Hypothesis generation: [Lab 7](/presentations/week7.qmd)
- Descriptive vs. Inferential statistics: [Lab 4](/presentations/week4.qmd), [Lab 6](/presentations/week6.qmd)
- Plots: [Lab 4](/presentations/week4.qmd)
- Histogram interpretations: [Lab 4](/presentations/week4.qmd), [Lab 6](/presentations/week6.qmd)
- CI calculation and interpretations: [Lab 4](/presentations/week4.qmd), [Lab 6](/presentations/week6.qmd), [Lab 7](/presentations/week7.qmd), [Online simulation](https://shiny.rit.albany.edu/stat/confidence/), [Lab11](/presentations/week11.qmd)
- p-value calculation and interpretations: [Lab 7](/presentations/week7.qmd), [Lab11](/presentations/week11.qmd)
- Paired t-test: [Lab 8](/presentations/week8.qmd)
- Effect size calculation: [Lab 9](/presentations/week9.qmd)
- Regression: [Lab 12](/presentations/week12.qmd); [Lab 13](/presentations/week13.qmd)

::::